// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talent.Infrastructure;

#nullable disable

namespace Talent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TalentDbContext))]
    [Migration("20260828164539_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Talent.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seniority");

                    b.PrimitiveCollection<string[]>("SkillIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skill_ids");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("WillingToRelocate")
                        .HasColumnType("boolean")
                        .HasColumnName("willing_to_relocate");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.HasIndex("Seniority")
                        .HasDatabaseName("ix_candidates_seniority");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_candidates_status");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("Talent.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Arrangement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrangement");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string[]>("RequiredSkillIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("required_skill_ids");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seniority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Arrangement")
                        .HasDatabaseName("ix_jobs_arrangement");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_jobs_title");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Talent.Domain.Entities.Candidate", b =>
                {
                    b.OwnsOne("Talent.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("CandidateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.HasKey("CandidateId");

                            b1.ToTable("candidates");

                            b1.WithOwner()
                                .HasForeignKey("CandidateId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Talent.Domain.Entities.Job", b =>
                {
                    b.OwnsOne("Talent.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.HasKey("JobId");

                            b1.ToTable("jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.OwnsOne("Talent.Domain.ValueObjects.SalaryRange", "Salary", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("salary_currency");

                            b1.Property<int>("Maximum")
                                .HasColumnType("integer")
                                .HasColumnName("salary_max");

                            b1.Property<int>("Minimum")
                                .HasColumnType("integer")
                                .HasColumnName("salary_min");

                            b1.HasKey("JobId");

                            b1.ToTable("jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Salary")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
