namespace Talent.Mcp.Tests.Tools;

using System.Text.Json;
using ModelContextProtocol.Protocol;
using Talent.Mcp.Toolkit.Caching;
using Talent.Mcp.Tools.Constants;
using Xunit;

/// <summary>
/// What <c>tools/list</c> must say. Not a smoke test: ADR-0002 measured a build where the server
/// started cleanly, logged nothing wrong, and answered <c>tools/list</c> with
/// <c>-32601 Method not available</c> because trimming had removed the reflection-discovered tools. A
/// test that only asserts the server starts would have shipped that.
/// </summary>
public sealed class ToolSurfaceTests
{
    /// <summary>The tools registered so far. Grows to all six as F2 lands the remaining two.</summary>
    private static readonly string[] Registered =
    [
        Mcp.ToolNames.SearchJobs,
        Mcp.ToolNames.GetJob,
        Mcp.ToolNames.ExtractSkills,
        Mcp.ToolNames.ScoreCandidateFit,
        Mcp.ToolNames.RejectCandidate,
    ];

    [Fact]
    public async Task Every_registered_tool_is_listed_by_name()
    {
        await using var harness = await ToolHarness.StartAsync();

        var tools = await harness.Client.ListToolsAsync();

        Assert.Equal(Registered, tools.Select(t => t.Name).ToArray());
    }

    [Fact]
    public async Task Listed_names_follow_the_canonical_order_not_the_alphabet()
    {
        await using var harness = await ToolHarness.StartAsync();

        var names = (await harness.Client.ListToolsAsync()).Select(t => t.Name).ToArray();

        // The guard against regressing to the SDK's own ordering. Measured 1 Sep 2026: without the
        // ordering filter the SDK returned these alphabetically, which is a different sequence — so
        // this assertion fails if the filter is removed, rather than passing by coincidence.
        Assert.Equal(Registered, names);
        Assert.NotEqual(names.OrderBy(static n => n, StringComparer.Ordinal).ToArray(), names);
    }

    [Fact]
    public async Task Order_is_stable_across_calls()
    {
        await using var harness = await ToolHarness.StartAsync();

        var first = (await harness.Client.ListToolsAsync()).Select(t => t.Name).ToArray();
        var second = (await harness.Client.ListToolsAsync()).Select(t => t.Name).ToArray();
        var third = (await harness.Client.ListToolsAsync()).Select(t => t.Name).ToArray();

        Assert.Equal(first, second);
        Assert.Equal(second, third);
    }

    [Fact]
    public async Task Canonical_name_list_covers_every_registered_tool()
    {
        await using var harness = await ToolHarness.StartAsync();

        var listed = (await harness.Client.ListToolsAsync()).Select(t => t.Name).ToArray();

        // Mcp.ToolNames.All is what the ordering filter sorts by, so a tool missing from it would sort
        // last silently. This is where that must be caught.
        Assert.All(listed, name => Assert.Contains(name, Mcp.ToolNames.All));
    }

    [Fact]
    public async Task Every_tool_declares_an_input_schema()
    {
        await using var harness = await ToolHarness.StartAsync();

        var tools = await harness.Client.ListToolsAsync();

        Assert.All(tools, tool =>
        {
            var schema = tool.ProtocolTool.InputSchema;

            // Mandatory in 2026-07-28: deserialization of a tool without one fails, and a client needs
            // it to build UI. Generated by the SDK from the method signature — this asserts its
            // presence, it does not author it.
            Assert.Equal(JsonValueKind.Object, schema.ValueKind);
            Assert.Equal("object", schema.GetProperty("type").GetString());
            Assert.True(schema.TryGetProperty("properties", out _), $"{tool.Name} has no properties.");
        });
    }

    [Fact]
    public async Task Injected_dependencies_are_not_exposed_as_tool_parameters()
    {
        await using var harness = await ToolHarness.StartAsync();

        var tools = await harness.Client.ListToolsAsync();

        // The tool methods take their use case as the first parameter. If the SDK ever bound those from
        // arguments instead of from services, the schema would demand a "search" object from the caller
        // and every call would fail — so this is asserted rather than assumed.
        Assert.All(tools, tool =>
        {
            var properties = tool.ProtocolTool.InputSchema.GetProperty("properties");

            Assert.All(
                new[] { "search", "getJob", "extract", "score", "reject", "handles", "options", "context", "cancellationToken" },
                injected => Assert.False(
                    properties.TryGetProperty(injected, out _),
                    $"{tool.Name} exposes the injected '{injected}' as a tool argument."));
        });
    }

    [Fact]
    public async Task Enum_parameters_are_declared_as_named_strings()
    {
        await using var harness = await ToolHarness.StartAsync();

        var tools = await harness.Client.ListToolsAsync();
        var arrangement = tools
            .Single(t => t.Name == Mcp.ToolNames.SearchJobs)
            .ProtocolTool.InputSchema
            .GetProperty("properties")
            .GetProperty("arrangement");

        // MCP9001 obsoleted the SDK's EnumSchema types (SEP-1330), and this domain reaches for enums in
        // tool inputs. Asserting the shape confirms the current generation path is the one in use: named
        // strings, not ordinals a caller would have to guess.
        Assert.Equal("string", arrangement.GetProperty("type").GetString());
        Assert.Equal(
            new[] { "Unspecified", "OnSite", "Hybrid", "Remote" },
            arrangement.GetProperty("enum").EnumerateArray().Select(v => v.GetString()).ToArray());
    }

    [Fact]
    public async Task The_region_header_is_declared_on_the_schema_not_hidden()
    {
        await using var harness = await ToolHarness.StartAsync();

        var tools = await harness.Client.ListToolsAsync();
        var region = tools
            .Single(t => t.Name == Mcp.ToolNames.GetJob)
            .ProtocolTool.InputSchema
            .GetProperty("properties")
            .GetProperty("region");

        // The SDK marks a promoted parameter with x-mcp-header rather than dropping it, so a client can
        // see that the value travels as a header. Worth pinning: if it were dropped, callers would have
        // no way to discover the routing knob exists.
        Assert.Equal(Mcp.RegionHeader, region.GetProperty("x-mcp-header").GetString());
    }

    [Fact]
    public async Task The_list_response_carries_the_cache_fields_the_revision_requires()
    {
        await using var harness = await ToolHarness.StartAsync();

        var result = await harness.Client
            .SendRequestAsync<ListToolsRequestParams, ListToolsResult>("tools/list", new ListToolsRequestParams());

        Assert.Equal(CachePolicies.ToolsList.TimeToLive, result.TimeToLive);
        Assert.Equal(CachePolicies.ToolsList.Scope, result.CacheScope);

        // Public, and the reason is specific rather than a default: all four tools go to every caller,
        // so one cached copy is correct for all of them. get_job's result is private for the opposite
        // reason — the Region header varies it and cacheScope has no Vary.
        Assert.Equal(CacheScope.Public, result.CacheScope);
    }

    [Fact]
    public async Task The_server_reports_its_identity_from_the_assembly()
    {
        await using var harness = await ToolHarness.StartAsync();

        var info = harness.Client.ServerInfo;

        Assert.Equal(Mcp.ServerName, info.Name);
        Assert.False(string.IsNullOrWhiteSpace(info.Version));

        // The version is read from the assembly so it cannot drift from the .csproj. A '+sha' suffix
        // would mean the source-revision stripping regressed.
        Assert.DoesNotContain('+', info.Version);
    }
}
